# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eTestData.proto\x12\x08TestData\"\xf5\x02\n\x17ReportTestResultRequest\x12\x10\n\x08isPassed\x18\x01 \x01(\x08\x12\x15\n\rspecification\x18\x02 \x01(\t\x12<\n\x08testType\x18\x03 \x01(\x0e\x32*.TestData.ReportTestResultRequest.TestType\x12\x44\n\x0ctestDataType\x18\x04 \x01(\x0e\x32..TestData.ReportTestResultRequest.TestDataType\"^\n\x08TestType\x12\n\n\x06\x45QUALS\x10\x00\x12\r\n\tNOTEQUALS\x10\x01\x12\x0e\n\nSTARTSWITH\x10\x02\x12\x0c\n\x08\x45NDSWITH\x10\x03\x12\n\n\x06INLIST\x10\x04\x12\r\n\tNOTINLIST\x10\x05\"M\n\x0cTestDataType\x12\r\n\tTYPE_BOOL\x10\x00\x12\x0c\n\x08TYPE_INT\x10\x01\x12\x0f\n\x0bTYPE_DOUBLE\x10\x02\x12\x0f\n\x0bTYPE_STRING\x10\x03\"\x07\n\x05\x45mpty\"\x16\n\x14ReportTestLogRequest\"\x14\n\x12GetTestStepRequest\"\x12\n\x10GetTestStepReply\"\x12\n\x10SetStatusRequest\"\x10\n\x0eSetStatusReply2\xa7\x02\n\x0fTestDataService\x12\x46\n\x10ReportTestResult\x12!.TestData.ReportTestResultRequest\x1a\x0f.TestData.Empty\x12@\n\rReportTestLog\x12\x1e.TestData.ReportTestLogRequest\x1a\x0f.TestData.Empty\x12G\n\x0bGetTestStep\x12\x1c.TestData.GetTestStepRequest\x1a\x1a.TestData.GetTestStepReply\x12\x41\n\tSetStatus\x12\x1a.TestData.SetStatusRequest\x1a\x18.TestData.SetStatusReplyB\x15\xaa\x02\x12Tremec.ScriptAgentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TestData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022Tremec.ScriptAgent'
  _globals['_REPORTTESTRESULTREQUEST']._serialized_start=29
  _globals['_REPORTTESTRESULTREQUEST']._serialized_end=402
  _globals['_REPORTTESTRESULTREQUEST_TESTTYPE']._serialized_start=229
  _globals['_REPORTTESTRESULTREQUEST_TESTTYPE']._serialized_end=323
  _globals['_REPORTTESTRESULTREQUEST_TESTDATATYPE']._serialized_start=325
  _globals['_REPORTTESTRESULTREQUEST_TESTDATATYPE']._serialized_end=402
  _globals['_EMPTY']._serialized_start=404
  _globals['_EMPTY']._serialized_end=411
  _globals['_REPORTTESTLOGREQUEST']._serialized_start=413
  _globals['_REPORTTESTLOGREQUEST']._serialized_end=435
  _globals['_GETTESTSTEPREQUEST']._serialized_start=437
  _globals['_GETTESTSTEPREQUEST']._serialized_end=457
  _globals['_GETTESTSTEPREPLY']._serialized_start=459
  _globals['_GETTESTSTEPREPLY']._serialized_end=477
  _globals['_SETSTATUSREQUEST']._serialized_start=479
  _globals['_SETSTATUSREQUEST']._serialized_end=497
  _globals['_SETSTATUSREPLY']._serialized_start=499
  _globals['_SETSTATUSREPLY']._serialized_end=515
  _globals['_TESTDATASERVICE']._serialized_start=518
  _globals['_TESTDATASERVICE']._serialized_end=813
# @@protoc_insertion_point(module_scope)
